# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(max_length=254)),
                ('text', models.TextField(max_length=2048)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 9, 10, 19, 23, 36, 703996, tzinfo=utc))),
            ],
        ),
    ]
