# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 11, 16, 30, 16, 572980, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(max_length=254),
        ),
    ]
